'
ohahohah/HowToBeAProgrammer pull request #4
Opened 2020-11-10 13:22 UTC by soheekim911

한국어 번역에 참여해주셔서 감사합니다. 여러분의 기여로 프로젝트가 더 풍성해지고 있습니다 :tada:
- PR 제목은 `이슈번호_파일경로`로 입력해주세요.
  - 예: `1_1.Beginner - Personal - Learn to debug`

## 작업 내용 
- 작업한 이슈 번호(예: #1):

## PR 전 확인하기
- [ ] PR(Pull Request) 전에 이슈를 먼저 생성하셨나요?
- [ ] 중복된 작업을 한 PR 이 없나요?
- [ ] Maintainer가 수정할 수 있도록 `Allow edits from maintainers` 항목을 체크하셨나요?
- [ ] (번역 작업이라면) 파일 이름은 원래 파일과 같게 `kr/` 폴더 밑에 위치해있나요?

2020-11-23 07:16 UTC, ohahohah commented on kr/1-Beginner/Personal-Skills/05-How-to-Understand-Performance-Problems.md
> +컴퓨터 시스템의 성능에는 많은 차원이 존재하며, 많은 종류의 리소스가 소비됩니다. 측정해야 하는 첫 번째 리소스는 *벽시계 시간(wall-clock time)*, 즉 계산하는 데에 걸리는 총 시간입니다. *벽시계 시간*을 로깅 하는 것은 다른 프로파일링을 실행할 수 없을 때 발생하는 예측불가능한 상황에 대해 알려준다는 점에서 특히 귀중합니다. 하지만, 이
일반적으로 wall-clock time 은 용어로 취급되어, 한국어 아티클에서도 wall-clock time 으로 영어 그대로 표기하는 경우가 많아보입니다. (참고. [구글 검색 결과](https://www.google.com/search?hl=ko&q=wall+clock+time))

`wall-clock time(벽시계 시간)` 으로 초기 표기는 영(한) 표기하고 두 번째 표기부터는 에는 `wall-clock time` 으로 해석하는 것은 어떨까요?

2020-11-23 07:30 UTC, ohahohah requested changes
번역에 참여해주셔서 감사합니다. 
제안 사항을 남겨두었습니다. 확인해주시면 감사하겠습니다.

2020-11-23 07:30 UTC, ohahohah commented on kr/1-Beginner/Personal-Skills/05-How-to-Understand-Performance-Problems.md
> +컴퓨터 시스템의 성능에는 많은 차원이 존재하며, 많은 종류의 리소스가 소비됩니다. 측정해야 하는 첫 번째 리소스는 *벽시계 시간(wall-clock time)*, 즉 계산하는 데에 걸리는 총 시간입니다. *벽시계 시간*을 로깅 하는 것은 다른 프로파일링을 실행할 수 없을 때 발생하는 예측불가능한 상황에 대해 알려준다는 점에서 특히 귀중합니다. 하지만, 이
일반적으로 wall-clock time 은 용어로 취급되어, 한국어 아티클에서도 wall-clock time 으로 영어 그대로 표기하는 경우가 많아보입니다. (참고. [구글 검색 결과](https://www.google.com/search?hl=ko&q=wall+clock+time))

`wall-clock time(벽시계 시간)` 으로 초기 표기는 영(한) 표기하고 두 번째 표기부터는 에는 `wall-clock time` 으로 해석하는 것은 어떨까요?

2020-11-29 14:47 UTC, soheekim911 commented on kr/1-Beginner/Personal-Skills/05-How-to-Understand-Performance-Problems.md
> +컴퓨터 시스템의 성능에는 많은 차원이 존재하며, 많은 종류의 리소스가 소비됩니다. 측정해야 하는 첫 번째 리소스는 *벽시계 시간(wall-clock time)*, 즉 계산하는 데에 걸리는 총 시간입니다. *벽시계 시간*을 로깅 하는 것은 다른 프로파일링을 실행할 수 없을 때 발생하는 예측불가능한 상황에 대해 알려준다는 점에서 특히 귀중합니다. 하지만, 이
일반적으로 사용하는 용어였군요..! 제안해 주신 대로 고쳐서 다시 커밋하겠습니다.

2020-11-29 14:55 UTC, soheekim911 commented on kr/1-Beginner/Personal-Skills/05-How-to-Understand-Performance-Problems.md
> +컴퓨터 시스템의 성능에는 많은 차원이 존재하며, 많은 종류의 리소스가 소비됩니다. 측정해야 하는 첫 번째 리소스는 *벽시계 시간(wall-clock time)*, 즉 계산하는 데에 걸리는 총 시간입니다. *벽시계 시간*을 로깅 하는 것은 다른 프로파일링을 실행할 수 없을 때 발생하는 예측불가능한 상황에 대해 알려준다는 점에서 특히 귀중합니다. 하지만, 이
혹시 영한 병기 형태에 대한 규칙도 따로 있을까요? 지금은 주로 `한(영)` 형태로 표기했는데, 괄호 없이 표기한다거나 하는 것이요.

2020-12-02 10:00 UTC, ohahohah approved these changes

2020-12-02 10:00 UTC, merged

2020-12-02 10:01 UTC, ohahohah commented
기여해주셔서 감사합니다. 반영하였습니다.