Translate 1-Beginner/Personal-Skills/07-How-to-Optimize-Loops
ohahohah/HowToBeAProgrammer pull request #9
Opened 2021-01-05 12:36 UTC by soheekim911

## 작업 내용 
- 작업한 이슈 번호(예: #1): #5

## PR 전 확인하기
- [x] PR(Pull Request) 전에 이슈를 먼저 생성하셨나요?
- [x] 중복된 작업을 한 PR 이 없나요?
- [x] Maintainer가 수정할 수 있도록 `Allow edits from maintainers` 항목을 체크하셨나요?
- [x] (번역 작업이라면) 파일 이름은 원래 파일과 같게 `kr/` 폴더 밑에 위치해있나요?

2021-01-05 12:52 UTC, ohahohah requested changes
번역에 참여해주셔서 감사합니다. 몇 가지 제안을 comment 로 남겨두었습니다. 고려해보시면 감사하겠습니다.

2021-01-05 12:52 UTC, ohahohah commented on kr/1-Beginner/Personal-Skills/07-How-to-Optimize-Loops.md
> +때로 당신은 제품에서 실행하는 데에 오랜 시간이 걸리거나 병목 현상을 일으키는 루프들(loops)이나 재귀 함수를 마주칠 것입니다. 루프를 좀 더 빠르게 만드는 시도를 하기 전에, 그것을 완전히 없앨 방법이 있는지 몇 분 동안 생각해 보세요. 다른 알고리즘을 사용하면 어떨까요? 다른 것을 계산하는 동안 그것을 동시에 계산할 수 있을까요? 이러한 방법으로도
`statement` 를 구문으로 번역하는 건 어떨까요? statement 자체가 cs 에서는 특정한 의미를 가집니다. 
한국에서는 '문' 으로 보통 번역을 합니다. (예. if statement -> if문 , for statement -> for문) 

관련된 내용도 첨부합니다. 
https://en.wikipedia.org/wiki/Statement_(computer_science)
https://ko.wikipedia.org/wiki/%EB%AC%B8_(%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D)

2021-01-05 12:52 UTC, ohahohah commented on kr/1-Beginner/Personal-Skills/07-How-to-Optimize-Loops.md
> +- 비싼 형 변환(typecasts)을 피합니다.
원문에서 이야기하는 `expensive` 라는 표현은 typecast 연산을 진행하는데 리소스를 많이 사용한다는 뜻입니다. 

'연산하는데 리소스를 많이 사용하는' 등으로 풀어서 번역하는 건 어떨까요? 
https://stackoverflow.com/a/1923902

2021-01-05 12:57 UTC, soheekim911 commented on kr/1-Beginner/Personal-Skills/07-How-to-Optimize-Loops.md
> +- 비싼 형 변환(typecasts)을 피합니다.
아하 그 편이 더 이해하기 쉽겠네요. 제안 감사드립니다!

2021-01-05 13:07 UTC, soheekim911 commented on kr/1-Beginner/Personal-Skills/07-How-to-Optimize-Loops.md
> +때로 당신은 제품에서 실행하는 데에 오랜 시간이 걸리거나 병목 현상을 일으키는 루프들(loops)이나 재귀 함수를 마주칠 것입니다. 루프를 좀 더 빠르게 만드는 시도를 하기 전에, 그것을 완전히 없앨 방법이 있는지 몇 분 동안 생각해 보세요. 다른 알고리즘을 사용하면 어떨까요? 다른 것을 계산하는 동안 그것을 동시에 계산할 수 있을까요? 이러한 방법으로도
안 그래도 어떻게 해석할까 고민했던 부분인데 감사합니다!

2021-01-06 04:45 UTC, ohahohah commented
@soheekim911 작업 중이실 때는  PR 앞에 `[WIP]` 키워드를 붙여주시면 구분이 가능합니다. 작업에 완료되시면 PR 제목 수정과 함께 comment 부탁드립니다.

2021-01-12 08:03 UTC, soheekim911 commented
> @soheekim911 작업 중이실 때는 PR 앞에 `[WIP]` 키워드를 붙여주시면 구분이 가능합니다. 작업에 완료되시면 PR 제목 수정과 함께 comment 부탁드립니다.

2021-01-12 08:12 UTC, soheekim911 commented
작업이 끝나서 WIP를 지웠습니다!

2021-01-12 09:47 UTC, ohahohah approved these changes

2021-01-12 09:47 UTC, merged